plugins:
  - rubocop-erb
  - rubocop-rake
  - rubocop-rspec

require:
  - sevencop

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/**/*.erb
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/RequireMFA:
  Enabled: false

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Sevencop/AutoloadOrdered:
  Enabled: true

Sevencop/HashElementOrdered:
  Enabled: true

Sevencop/MethodDefinitionArgumentsMultiline:
  Enabled: true

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Enabled: true

Sevencop/MethodDefinitionOrdered:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
