inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  Include:
    - '**/*.erb'

Layout/ArgumentAlignment:
  Exclude:
    - '**/*.erb'

Layout/ArrayAlignment:
  Exclude:
    - '**/*.erb'

Layout/BlockAlignment:
  Exclude:
    - '**/*.erb'

Layout/ClosingParenthesisIndentation:
  Exclude:
    - '**/*.erb'

Layout/CommentIndentation:
  Exclude:
    - '**/*.erb'

# Indentation follows the containing ERB tag, not the file as a whole.
Layout/InitialIndentation:
  Exclude:
    - '**/*.erb'

Layout/ElseAlignment:
  Exclude:
    - '**/*.erb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - '**/*.erb'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - '**/*.erb'

Layout/EndAlignment:
  Exclude:
    - '**/*.erb'

Layout/ExtraSpacing:
  Exclude:
    - '**/*.erb'

Layout/FirstArgumentIndentation:
  Exclude:
    - '**/*.erb'

Layout/FirstArrayElementIndentation:
  Exclude:
    - '**/*.erb'

Layout/FirstArrayElementLineBreak:
  Exclude:
    - '**/*.erb'

Layout/FirstHashElementIndentation:
  Exclude:
    - '**/*.erb'

Layout/FirstHashElementLineBreak:
  Exclude:
    - '**/*.erb'

Layout/FirstMethodArgumentLineBreak:
  Exclude:
    - '**/*.erb'

Layout/FirstParameterIndentation:
  Exclude:
    - '**/*.erb'

Layout/HashAlignment:
  Exclude:
    - '**/*.erb'

Layout/IndentationConsistency:
  Exclude:
    - '**/*.erb'

Layout/IndentationWidth:
  Exclude:
    - '**/*.erb'

Layout/LeadingEmptyLine:
  Exclude:
    - '**/*.erb'

# Non-Ruby content gives false positives for this cop.
Layout/LeadingEmptyLines:
  Exclude:
    - '**/*.erb'

Layout/LineEndStringConcatenationIndentation:
  Exclude:
    - '**/*.erb'

Layout/LineLength:
  Exclude:
    - '**/*.erb'

Layout/MultilineArrayBraceLayout:
  Exclude:
    - '**/*.erb'

Layout/MultilineAssignmentLayout:
  Exclude:
    - '**/*.erb'

Layout/MultilineHashBraceLayout:
  Exclude:
    - '**/*.erb'

Layout/MultilineMethodCallBraceLayout:
  Exclude:
    - '**/*.erb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - '**/*.erb'

Layout/MultilineMethodDefinitionBraceLayout:
  Exclude:
    - '**/*.erb'

Layout/MultilineOperationIndentation:
  Exclude:
    - '**/*.erb'

Layout/ParameterAlignment:
  Exclude:
    - '**/*.erb'

Layout/SpaceBeforeSemicolon:
  Exclude:
    - '**/*.erb'

# Non-Ruby content gives false positives for this cop.
Layout/TrailingEmptyLines:
  Exclude:
    - '**/*.erb'

Layout/TrailingWhitespace:
  Exclude:
    - '**/*.erb'

Lint/DuplicateBranch:
  Exclude:
    - '**/*.erb'

Lint/EmptyBlock:
  Exclude:
    - '**/*.erb'

Lint/EmptyConditionalBody:
  Exclude:
    - '**/*.erb'

# Non-Ruby content gives false positives for this cop.
Lint/EmptyFile:
  Exclude:
    - '**/*.erb'

Lint/EmptyWhen:
  Exclude:
    - '**/*.erb'

Lint/Void:
  Exclude:
    - '**/*.erb'

Style/EmptyElse:
  Exclude:
    - '**/*.erb'

# ERB doesn't support magic comments.
Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*.erb'

Style/IdenticalConditionalBranches:
  Exclude:
    - '**/*.erb'

Style/IfInsideElse:
  Exclude:
    - '**/*.erb'

Style/IfUnlessModifier:
  Exclude:
    - '**/*.erb'

Style/IfWithSemicolon:
  Exclude:
    - '**/*.erb'

Style/MultilineTernaryOperator:
  Exclude:
    - '**/*.erb'

Style/NestedTernaryOperator:
  Exclude:
    - '**/*.erb'

Style/Next:
  Exclude:
    - '**/*.erb'

Style/ParallelAssignment:
  Exclude:
    - '**/*.erb'

Style/RedundantCondition:
  Exclude:
    - '**/*.erb'

Style/RescueModifier:
  Exclude:
    - '**/*.erb'

Style/SafeNavigation:
  Exclude:
    - '**/*.erb'

Style/Semicolon:
  Exclude:
    - '**/*.erb'

Style/SoleNestedConditional:
  Exclude:
    - '**/*.erb'

Style/SymbolProc:
  Exclude:
    - '**/*.erb'

Style/TrailingCommaInArguments:
  Exclude:
    - '**/*.erb'

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - '**/*.erb'

Style/TrailingCommaInHashLiteral:
  Exclude:
    - '**/*.erb'

Style/WhileUntilDo:
  Exclude:
    - '**/*.erb'

Style/WhileUntilModifier:
  Exclude:
    - '**/*.erb'
